name: Continuous Integration / Continuous Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
######## Continuous Integration
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: pip install -r src/requirements.txt

      - name: Test with pytest ### Unitests
        working-directory: src
        run: pytest tests.py

      - name: Check linting ### Quality test
        working-directory: src
        run: ruff check .

  SAST:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Bandit Version
        run: |
          pip install bandit
          bandit --version

      - name: Security Compliance using Bandit
        run: |
          bandit -r . -ll > bandit_output.txt 
          if grep -q "Severity: HIGH" bandit_output.txt; then
            echo "High severity issues found!"
            cat bandit_output.txt
            exit 1  # Falla solo en HIGH severity
          fi
          echo "Security matches the criteria"
  
  CD:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghrc.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/Mariscurrena/Calculadora-CI-CD:latest