name: Continuous Integration / Continuous Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
######## Continuous Integration
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: pip install -r src/requirements.txt

      - name: Test with pytest ### Unitests
        working-directory: src
        run: pytest tests.py

      - name: Check linting ### Quality test
        working-directory: src
        run: ruff check .

      - name: Check Bandit Version
        run: bandit --version

      - name: Security Compliance using Bandit
        run: |
          bandit -r . > bandit_output.txt
          if grep -q "Severity: HIGH" bandit_output.txt; then
            echo "High severity issues found!"
            cat bandit_output.txt
            exit 1
          fi
          echo "Security matches the criteria"