name: Continuous Integration / Continuous Delivery

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4