name: Continuous Integration / Continuous Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
######## Continuous Integration
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: pip install -r src/requirements.txt

      - name: Test with pytest ### Unitests
        working-directory: src
        run: pytest tests.py

      - name: Check linting ### Quality test
        working-directory: src
        run: ruff check .

