name: Continuous Integration / Continuous Delivery

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
######## Continuous Integration
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: pip install -r src/requirements.txt

      - name: Test with pytest ### Unitests
        working-directory: src
        run: pytest tests.py

      - name: Check linting ### Quality test
        working-directory: src
        run: ruff check .

      - name: Check Bandit Version
        run: bandit --version

      - name: Security Compliance using Bandit
        run: |
          bandit -r . -ll > bandit_output.txt 
          if grep -q "Severity: HIGH" bandit_output.txt; then
            echo "High severity issues found!"
            cat bandit_output.txt
            exit 1  # Falla solo en HIGH severity
          fi
          echo "Security matches the criteria"
  
  SCA:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OWASP Dependency-Check
        run: |
          pip install dependency-check

      - name: Run Dependency-Check
        run: |
          dependency-check --project MyProject --scan ./src --format HTML --out ./dependency-check-report

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report/*.html

      - name: Check for Vulnerabilities (HIGH Severity)
        run: |
          if grep -q "HIGH" ./dependency-check-report/*; then
            echo "High severity vulnerabilities found!"
            exit 1
          else
            echo "No high severity vulnerabilities found."
          fi